[workspace]
authors = ["JJ-BradleyBare <bradleybare@gmail.com>"]
channels = ["conda-forge"]
name = "lab-flow-sim"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
python = "3.13.*"
django = ">=6.0.2,<7"
streamlit = ">=1.54.0,<2"
simpy = ">=4.1.1,<5"

[pypi-dependencies]
streamlit-flow-component = { git = "https://github.com/BirdBare/streamlit-flow" }
