[workspace]
authors = ["JJ-BradleyBare <bradleybare@gmail.com>"]
channels = ["conda-forge"]
name = "lab-flow-sim"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
orm_delete = { cmd="python reset_db.py", cwd="src/orm"}

orm_update = { cmd="python manage.py makemigrations", cwd="src/orm"}

orm_upgrade = { cmd="python manage.py migrate", cwd="src/orm"}

orm_reset = { depends-on=["orm_delete","orm_update","orm_upgrade"]}

webapp = {cmd = "streamlit run home.py", cwd="src/webapp"}

[dependencies]
python = "3.13.*"
django = ">=6.0.2,<7"
streamlit = ">=1.54.0,<2"
simpy = ">=4.1.1,<5"

[pypi-dependencies]
streamlit-flow-component = { git = "https://github.com/BirdBare/streamlit-flow" }
