# Generated by Django 6.0.1 on 2026-02-12 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0001_initial'),
        ('workcell', '0004_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='labware',
            name='workcell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workcell.workcell'),
            preserve_default=False,
        ),
    ]
