# Generated by Django 6.0.1 on 2026-02-20 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('device', '0003_rename_comment_function_comments'),
        ('labware', '0002_labware_workcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polymorphic_content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StepIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('base_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.basestep')),
            ],
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier_formula', models.CharField(max_length=255)),
                ('labware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labware.labware')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.process')),
            ],
        ),
        migrations.AddField(
            model_name='basestep',
            name='swimlane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.swimlane'),
        ),
        migrations.CreateModel(
            name='SwimlaneIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('swimlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.swimlane')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workcell_process.basestep')),
                ('parallelization_key', models.CharField(blank=True, max_length=255)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.function')),
            ],
            bases=('workcell_process.basestep',),
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workcell_process.basestep')),
                ('connected_swimlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.swimlane')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell_process.process')),
            ],
            bases=('workcell_process.basestep',),
        ),
    ]
