# Generated by Django 6.0.1 on 2026-02-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0005_delete_process'),
        ('workcell_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='workcell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workcell.workcell'),
            preserve_default=False,
        ),
    ]
