# Generated by Django 6.0.1 on 2026-02-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcell_process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimlane',
            old_name='labware',
            new_name='resource',
        ),
    ]
