# Generated by Django 5.2.5 on 2026-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcell_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimlane',
            name='labware',
        ),
        migrations.AddField(
            model_name='swimlane',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
