# Generated by Django 6.0.2 on 2026-02-27 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workcell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('workcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell.workcell')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField()),
                ('device_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workcell.assigneddevice')),
                ('device_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workcell.assigneddevice')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell.workcell')),
            ],
        ),
    ]
