# Generated by Django 6.0.1 on 2026-02-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconnection',
            name='assigned_devices',
        ),
        migrations.AddField(
            model_name='deviceconnection',
            name='device_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workcell.assigneddevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceconnection',
            name='device_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workcell.assigneddevice'),
            preserve_default=False,
        ),
    ]
