# Generated by Django 6.0.1 on 2026-01-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconnection',
            name='distance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
