# Generated by Django 5.2.5 on 2026-02-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0002_remove_deviceconnection_assigned_devices_and_more'),
        ('workcell_process', '0002_remove_swimlane_labware_swimlane_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labware',
        ),
    ]
