# Generated by Django 6.0.1 on 2026-02-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0002_deviceconnection_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcell',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
