# Generated by Django 6.0.1 on 2026-02-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0002_remove_deviceconnection_assigned_devices_and_more'),
        ('workcell_process', '0002_rename_labware_swimlane_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labware',
            new_name='Resource',
        ),
    ]
