# Generated by Django 6.0.1 on 2026-02-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcell', '0004_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
