# Generated by Django 6.0.1 on 2026-01-30 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workcell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_pos', models.PositiveIntegerField()),
                ('y_pos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignedDeviceNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcell.assigneddevice')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_diagram.node')),
            ],
        ),
    ]
