# Generated by Django 6.0.2 on 2026-03-05 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_diagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('left', 'left'), ('right', 'right')], max_length=10)),
                ('is_source', models.BooleanField()),
                ('is_target', models.BooleanField()),
                ('valid_targets', models.ManyToManyField(to='flow_diagram.handle')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='handles',
            field=models.ManyToManyField(to='flow_diagram.handle'),
        ),
    ]
