# Generated by Django 6.0.2 on 2026-03-05 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_diagram', '0002_handle_node_handles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flow_diagram.handle')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flow_diagram.node')),
                ('target_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flow_diagram.handle')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flow_diagram.node')),
            ],
        ),
    ]
