# Generated by Django 6.0.3 on 2026-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='category',
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('Spatial', 'Spatial'), ('Material', 'Material')], default='Material', max_length=255),
            preserve_default=False,
        ),
    ]
