# Generated by Django 6.0.1 on 2026-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
