# Generated by Django 6.0.1 on 2026-02-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_function_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='comment',
            new_name='comments',
        ),
    ]
